let player,playerReady=false,results=[],currentIndex=-1,progressTimer;const $=s=>document.querySelector(s);const key=window.LUMI_CONFIG?.YOUTUBE_API_KEY;
function toast(message){const e=$('#toast');e.textContent=message;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2600)}
window.onYouTubeIframeAPIReady=()=>{player=new YT.Player('youtubePlayer',{height:'190',width:'338',playerVars:{playsinline:1,rel:0},events:{onReady:()=>{playerReady=true},onStateChange:onPlayerStateChange}})};
function onPlayerStateChange(e){$('#playBtn').textContent=e.data===YT.PlayerState.PLAYING?'❚❚':'▶';if(e.data===YT.PlayerState.PLAYING)startTimer();else clearInterval(progressTimer);if(e.data===YT.PlayerState.ENDED)next()}
async function search(){const q=$('#searchInput').value.trim();if(!q)return toast('Nhập tên bài hát hoặc ca sĩ trước nhé');if(!key)return toast('Chưa có API key: hãy tạo file config.local.js');$('#playlistTitle').textContent='Đang tìm “'+q+'”...';try{const url='https://www.googleapis.com/youtube/v3/search?part=snippet&type=video&videoCategoryId=10&maxResults=12&q='+encodeURIComponent(q)+'&key='+encodeURIComponent(key);const response=await fetch(url);const data=await response.json();if(!response.ok)throw new Error(data.error?.message||'Không thể tìm nhạc');results=data.items||[];renderResults();$('#playlistTitle').textContent='Kết quả cho “'+q+'”'}catch(error){$('#playlistTitle').textContent='Không thể tìm kiếm';toast(error.message)}} 
function renderResults(){const list=$('#playlist');list.innerHTML='';if(!results.length){list.innerHTML='<p class="muted">Không tìm thấy bài phù hợp.</p>';return}results.forEach((item,i)=>{const s=item.snippet,e=document.createElement('article');e.className='track';e.innerHTML='<img class="thumb" src="'+s.thumbnails.medium.url+'" alt=""/><button class="track-info"><strong>'+escapeHtml(s.title)+'</strong><span>'+escapeHtml(s.channelTitle)+'</span></button><button class="like" title="Phát bài này">▶</button>';e.querySelector('.track-info').onclick=()=>playItem(i);e.querySelector('.like').onclick=()=>playItem(i);list.append(e)})}
function escapeHtml(t){const d=document.createElement('div');d.textContent=t;return d.innerHTML}
function playItem(i){if(!playerReady)return toast('Trình phát YouTube đang tải...');currentIndex=i;const s=results[i].snippet;player.loadVideoById(results[i].id.videoId);$('#nowTitle').textContent=s.title;$('#nowArtist').textContent=s.channelTitle;$('#featureTitle').textContent=s.title;$('#featureArtist').textContent=s.channelTitle;$('#playerFallback').style.display='none'}
function toggle(){if(!playerReady)return toast('Trình phát YouTube đang tải...');player.getPlayerState()===YT.PlayerState.PLAYING?player.pauseVideo():player.playVideo()}function next(){if(results.length)playItem((currentIndex+1+results.length)%results.length)}function prev(){if(results.length)playItem((currentIndex-1+results.length)%results.length)}function startTimer(){clearInterval(progressTimer);progressTimer=setInterval(()=>{if(!playerReady)return;const now=player.getCurrentTime(),total=player.getDuration();if(total){$('#progress').value=now/total*100;$('#currentTime').textContent=format(now);$('#duration').textContent=format(total)}},500)}function format(s){return Math.floor(s/60)+':'+String(Math.floor(s%60)).padStart(2,'0')}
$('#searchBtn').onclick=search;$('#searchInput').onkeydown=e=>{if(e.key==='Enter')search()};$('#playFeatured').onclick=()=>{$('#searchInput').value='nhạc chill';search()};$('#clearBtn').onclick=()=>{results=[];$('#playlist').innerHTML='';$('#playlistTitle').textContent='Tìm một bài để bắt đầu'};$('#playBtn').onclick=toggle;$('#nextBtn').onclick=next;$('#prevBtn').onclick=prev;$('#muteBtn').onclick=()=>{if(!playerReady)return;player.isMuted()?player.unMute():player.mute();$('#muteBtn').textContent=player.isMuted()?'♩':'♬'};$('#progress').oninput=e=>{if(playerReady&&player.getDuration())player.seekTo(e.target.value/100*player.getDuration(),true)};document.querySelectorAll('.mood').forEach(b=>b.onclick=()=>{$('#searchInput').value=b.dataset.query;search()});if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');